#### Author: Taiwo
name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy only on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      #  Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      #  Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Match your project version

      #  Install dependencies
      - name: Install dependencies
        run: npm install


      #  Build React project
      - name: Build project
        run: npm run build
        continue-on-error: false  # Stops workflow if build fails

      #  Deploy to Vercel only if build succeeds
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN --confirm
